// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"go-template/domain/entities"
	"sync"
)

// ExampleUseCaseMock is a mock implementation of v1.ExampleUseCase.
//
//	func TestSomethingThatUsesExampleUseCase(t *testing.T) {
//
//		// make and configure a mocked v1.ExampleUseCase
//		mockedExampleUseCase := &ExampleUseCaseMock{
//			CreateExampleFunc: func(ctx context.Context, example entities.Example) (string, error) {
//				panic("mock out the CreateExample method")
//			},
//			GetExampleByIDFunc: func(ctx context.Context, id string) (entities.Example, error) {
//				panic("mock out the GetExampleByID method")
//			},
//		}
//
//		// use mockedExampleUseCase in code that requires v1.ExampleUseCase
//		// and then make assertions.
//
//	}
type ExampleUseCaseMock struct {
	// CreateExampleFunc mocks the CreateExample method.
	CreateExampleFunc func(ctx context.Context, example entities.Example) (string, error)

	// GetExampleByIDFunc mocks the GetExampleByID method.
	GetExampleByIDFunc func(ctx context.Context, id string) (entities.Example, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateExample holds details about calls to the CreateExample method.
		CreateExample []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Example is the example argument value.
			Example entities.Example
		}
		// GetExampleByID holds details about calls to the GetExampleByID method.
		GetExampleByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockCreateExample  sync.RWMutex
	lockGetExampleByID sync.RWMutex
}

// CreateExample calls CreateExampleFunc.
func (mock *ExampleUseCaseMock) CreateExample(ctx context.Context, example entities.Example) (string, error) {
	callInfo := struct {
		Ctx     context.Context
		Example entities.Example
	}{
		Ctx:     ctx,
		Example: example,
	}
	mock.lockCreateExample.Lock()
	mock.calls.CreateExample = append(mock.calls.CreateExample, callInfo)
	mock.lockCreateExample.Unlock()
	if mock.CreateExampleFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.CreateExampleFunc(ctx, example)
}

// CreateExampleCalls gets all the calls that were made to CreateExample.
// Check the length with:
//
//	len(mockedExampleUseCase.CreateExampleCalls())
func (mock *ExampleUseCaseMock) CreateExampleCalls() []struct {
	Ctx     context.Context
	Example entities.Example
} {
	var calls []struct {
		Ctx     context.Context
		Example entities.Example
	}
	mock.lockCreateExample.RLock()
	calls = mock.calls.CreateExample
	mock.lockCreateExample.RUnlock()
	return calls
}

// GetExampleByID calls GetExampleByIDFunc.
func (mock *ExampleUseCaseMock) GetExampleByID(ctx context.Context, id string) (entities.Example, error) {
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetExampleByID.Lock()
	mock.calls.GetExampleByID = append(mock.calls.GetExampleByID, callInfo)
	mock.lockGetExampleByID.Unlock()
	if mock.GetExampleByIDFunc == nil {
		var (
			exampleOut entities.Example
			errOut     error
		)
		return exampleOut, errOut
	}
	return mock.GetExampleByIDFunc(ctx, id)
}

// GetExampleByIDCalls gets all the calls that were made to GetExampleByID.
// Check the length with:
//
//	len(mockedExampleUseCase.GetExampleByIDCalls())
func (mock *ExampleUseCaseMock) GetExampleByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetExampleByID.RLock()
	calls = mock.calls.GetExampleByID
	mock.lockGetExampleByID.RUnlock()
	return calls
}
