// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"go-template/domain/entities"
	"sync"
)

// SettingsUseCaseMock is a mock implementation of admin.SettingsUseCase.
//
//	func TestSomethingThatUsesSettingsUseCase(t *testing.T) {
//
//		// make and configure a mocked admin.SettingsUseCase
//		mockedSettingsUseCase := &SettingsUseCaseMock{
//			GetSettingsFunc: func(ctx context.Context) (*entities.SystemSettings, error) {
//				panic("mock out the GetSettings method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, settings *entities.SystemSettings) error {
//				panic("mock out the UpdateSettings method")
//			},
//		}
//
//		// use mockedSettingsUseCase in code that requires admin.SettingsUseCase
//		// and then make assertions.
//
//	}
type SettingsUseCaseMock struct {
	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (*entities.SystemSettings, error)

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, settings *entities.SystemSettings) error

	// calls tracks calls to the methods.
	calls struct {
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Settings is the settings argument value.
			Settings *entities.SystemSettings
		}
	}
	lockGetSettings    sync.RWMutex
	lockUpdateSettings sync.RWMutex
}

// GetSettings calls GetSettingsFunc.
func (mock *SettingsUseCaseMock) GetSettings(ctx context.Context) (*entities.SystemSettings, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	if mock.GetSettingsFunc == nil {
		var (
			systemSettingsOut *entities.SystemSettings
			errOut            error
		)
		return systemSettingsOut, errOut
	}
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedSettingsUseCase.GetSettingsCalls())
func (mock *SettingsUseCaseMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *SettingsUseCaseMock) UpdateSettings(ctx context.Context, settings *entities.SystemSettings) error {
	callInfo := struct {
		Ctx      context.Context
		Settings *entities.SystemSettings
	}{
		Ctx:      ctx,
		Settings: settings,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	if mock.UpdateSettingsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateSettingsFunc(ctx, settings)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockedSettingsUseCase.UpdateSettingsCalls())
func (mock *SettingsUseCaseMock) UpdateSettingsCalls() []struct {
	Ctx      context.Context
	Settings *entities.SystemSettings
} {
	var calls []struct {
		Ctx      context.Context
		Settings *entities.SystemSettings
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}
